osx_image: xcode11
language: objective-c
cache:
  directories:
  - Carthage
env:
  global:
  - FRAMEWORK_NAME=TapestryDemo
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
script:
- xcodebuild -project Example/TapestryDemoExample.xcodeproj -scheme TapestryDemoExample -sdk iphonesimulator -destination 'OS=13.0,name=iPhone XÊ€,platform=iOS Simulator' -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c