name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Create a new release
        uses: fortmarek/tapestry-action@master
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}