name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Write a secret
        run: |
          sudo mkdir -p /opt/ejson/keys/
          sudo touch /opt/ejson/keys/file
          sudo echo "$GITHUB_ACTOR" > file
      - name: Create a new release
        uses: fortmarek/tapestry-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
